In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2])

In [3]:
a.dtype

dtype('int32')

In [4]:
b= np.array([0,1,2] ,dtype = 'float32')

In [5]:
b

array([0., 1., 2.], dtype=float32)

In [6]:
c = a.astype('float32')
c

array([0., 1., 2.], dtype=float32)

In [7]:
two_d_arr = np.array([[1,2,3],[4,5,6]])
two_d_arr.shape

(2, 3)

#### Arrays can also be reshaped as long as the product of the shape dimensions is equal to the total number of elements in the array

In [8]:
another_two_d_arr = two_d_arr.reshape(3,2)
another_two_d_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
x = np.array(range(0,16))

In [10]:
y = x.reshape(4,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
all_zeros = np.zeros((3,3))
all_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
all_empty = np.empty((3,3))
all_empty

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
all_ones  = np.ones((3,3))
all_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.random.rand(3, 3) 

array([[0.6483527 , 0.74533179, 0.08526147],
       [0.04190261, 0.21875718, 0.87229125],
       [0.44863389, 0.14735965, 0.76033318]])

In [15]:
y_allzeros  = np.zeros_like(y)
y_allzeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
y_allones  = np.ones_like(y_allzeros)
y_allones
#np.empty_like(y_allzeros)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

####  Accessing Arrays

In [17]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]) 

In [18]:
A[0]

0

In [19]:
A = A.reshape(3,3)

In [20]:
A[0, 1] 

1

In [21]:
A[0:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
A[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [23]:
A[0, 1] = 8 
A[0:2, 0:2] = np.ones((2,2))

In [24]:
A[0:2, 0:2]

array([[1, 1],
       [1, 1]])

##### Indexing with the slicing syntax is very fast because, unlike lists, it doesn't produce a copy of the array. In NumPy's terminology, it returns a view of the same memory area. If we take a slice of the original array, and then we change one of its values, the original array will be updated as well.
##### To prevent side effects, you can set the a.flags.writeable = False flag, which will prevent accidental mutation of the array or any of its views.

##### Accessing arrays

In [25]:
nums = np.array(range(0,16))

In [26]:
nums = nums.reshape(4,4)

In [27]:
nums

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
print(nums[0])

[0 1 2 3]


In [29]:
print(nums[0,1])

1


In [32]:
print(nums[0:2])

[[0 1 2 3]
 [4 5 6 7]]


In [34]:
print(nums[1:,3])

[ 7 11 15]


In [36]:
print(nums[:2,3])

[3 7]


In [37]:
print(nums[0:2,0:2])

[[0 1]
 [4 5]]


In [38]:
a = np.array([0, 1, 2, 3, 4, 5]) 
mask = np.array([True, False, True, False, False, False]) 
a[mask] 

array([0, 2])

In [43]:
r_i = np.random.rand(100, 2) 
idx = np.arange(50)

In [44]:
%timeit np.take(r_i, idx, axis=0) 

3.84 µs ± 159 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [45]:
%timeit r_i[idx] 

3.97 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
